services:
  - type: cron
    name: gmail-telegram-cron
    runtime: python
    schedule: "*/15 * * * *"  # cada 15 minutos
    envVars:
      - key: GMAIL_USER
        fromEnvVar: GMAIL_USER
      - key: GMAIL_PASS
        fromEnvVar: GMAIL_PASS
      - key: TELEGRAM_BOT_TOKEN
        fromEnvVar: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromEnvVar: TELEGRAM_CHAT_ID
    buildCommand: ""
    startCommand: "python gmail_to_telegram.py"
